/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Image;
import model.User;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;


/**
 *
 * @author Ronald
 */
public class UserJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserJFrame.class.getName());
    private File selectedPhoto;
    private File photo;
    
    /**
     * Creates new form UserJFrame
     */
    public UserJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.JLabel();
        photoTextfield = new javax.swing.JTextField();
        Phone = new javax.swing.JLabel();
        uploadbutton = new javax.swing.JButton();
        phoneFormattedtextfield = new javax.swing.JFormattedTextField();
        LastNameTextfield = new javax.swing.JTextField();
        Lastname = new javax.swing.JLabel();
        continentLabel = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        continentComboBox = new javax.swing.JComboBox<>();
        Submitbutton = new javax.swing.JButton();
        experience = new javax.swing.JLabel();
        FirstnameTextfield = new javax.swing.JTextField();
        Photo = new javax.swing.JLabel();
        AgeSpinner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        experienceTextArea = new javax.swing.JTextArea();
        firstname = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        email = new javax.swing.JLabel();
        emailFormattedTextField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gender.setText("Gender");

        photoTextfield.addActionListener(this::photoTextfieldActionPerformed);

        Phone.setText("Phone:");

        uploadbutton.setText("Upload Photo");
        uploadbutton.addActionListener(this::uploadbuttonActionPerformed);

        try {
            phoneFormattedtextfield.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phoneFormattedtextfield.setToolTipText("123-456-7890");
        phoneFormattedtextfield.addActionListener(this::phoneFormattedtextfieldActionPerformed);

        Lastname.setText("Last Name:");

        continentLabel.setText("Continent:");

        Age.setText("Age:");

        continentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Africa", "Antarctica", "Asia", "Europe", "North America", "South America", "Australia" }));

        Submitbutton.setText("Submit");
        Submitbutton.addActionListener(this::SubmitbuttonActionPerformed);

        experience.setText("Experience:");

        Photo.setText("Photo:");

        AgeSpinner.setModel(new javax.swing.SpinnerNumberModel());

        experienceTextArea.setColumns(20);
        experienceTextArea.setRows(5);
        jScrollPane1.setViewportView(experienceTextArea);

        firstname.setText("First Name:");

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        email.setText("Email");

        emailFormattedTextField.addActionListener(this::emailFormattedTextFieldActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lastname)
                            .addComponent(Age)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(Submitbutton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Phone)
                            .addComponent(email)
                            .addComponent(experience)
                            .addComponent(Photo))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(photoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(uploadbutton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(continentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(phoneFormattedtextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addComponent(emailFormattedTextField)))
                        .addGap(0, 405, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(continentLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gender)
                                    .addComponent(firstname))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstnameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AgeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname)
                    .addComponent(FirstnameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lastname)
                    .addComponent(LastNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Age))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Phone)
                    .addComponent(phoneFormattedtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(emailFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continentLabel)
                    .addComponent(continentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(experience)
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Photo)
                                    .addComponent(photoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uploadbutton)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Submitbutton)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void photoTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoTextfieldActionPerformed

    }//GEN-LAST:event_photoTextfieldActionPerformed

    private void uploadbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadbuttonActionPerformed
 
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg", "png", "jpeg"));
    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        selectedPhoto = fileChooser.getSelectedFile();
        photoTextfield.setText(selectedPhoto.getAbsolutePath()); // <-- shows the file path in the textfield
        JOptionPane.showMessageDialog(this, "Photo uploaded: " + selectedPhoto.getName());
    }

    }//GEN-LAST:event_uploadbuttonActionPerformed

    private void phoneFormattedtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFormattedtextfieldActionPerformed

    }//GEN-LAST:event_phoneFormattedtextfieldActionPerformed

    private void SubmitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbuttonActionPerformed

        // Read all input fields
    String firstName = FirstnameTextfield.getText().trim();
    String lastName = LastNameTextfield.getText().trim();
    String gender = genderComboBox.getSelectedItem().toString();
    int age = (Integer) AgeSpinner.getValue();
    String phone = phoneFormattedtextfield.getText().trim();
    String email = emailFormattedTextField.getText().trim();
    String continent = continentComboBox.getSelectedItem().toString();
    String experience = experienceTextArea.getText().trim();

    // === Validation ===
    if (firstName.isEmpty() || lastName.isEmpty() || phone.isEmpty() || email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
  if (!phone.matches("\\d{3}-\\d{3}-\\d{4}")) {
    JOptionPane.showMessageDialog(this, "Please enter a valid phone number (e.g., 123-456-7890)",
        "Invalid Phone", ERROR_MESSAGE);
    phoneFormattedtextfield.requestFocus();
    return;
}
    
    if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
        JOptionPane.showMessageDialog(this, "Invalid email format!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

if (selectedPhoto == null) {
    JOptionPane.showMessageDialog(this, "Please upload a photo!", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}
    // === Create User object with uploaded photo ===
   User user = new User(firstName, lastName, gender, age, phone, email, continent, experience, selectedPhoto);

    // === Show success popup with user.toString() ===
    if (selectedPhoto != null) {
        ImageIcon icon = new ImageIcon(new ImageIcon(selectedPhoto.getAbsolutePath())
                .getImage().getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH));
        JOptionPane.showMessageDialog(this, user.toString(), "Profile", JOptionPane.INFORMATION_MESSAGE, icon);
    } else {
        JOptionPane.showMessageDialog(this, user.toString(), "Profile", JOptionPane.INFORMATION_MESSAGE);
    }
    
    

    }//GEN-LAST:event_SubmitbuttonActionPerformed

    private void emailFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFormattedTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JSpinner AgeSpinner;
    private javax.swing.JTextField FirstnameTextfield;
    private javax.swing.JTextField LastNameTextfield;
    private javax.swing.JLabel Lastname;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel Photo;
    private javax.swing.JButton Submitbutton;
    private javax.swing.JComboBox<String> continentComboBox;
    private javax.swing.JLabel continentLabel;
    private javax.swing.JLabel email;
    private javax.swing.JFormattedTextField emailFormattedTextField;
    private javax.swing.JLabel experience;
    private javax.swing.JTextArea experienceTextArea;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField phoneFormattedtextfield;
    private javax.swing.JTextField photoTextfield;
    private javax.swing.JButton uploadbutton;
    // End of variables declaration//GEN-END:variables
}
